name: setup-uv
description: astral-sh/setup-uv pinned by commit SHA
inputs:
  enable-cache:
    description: Enable uv cache
    required: false
    default: "auto"
  save-cache:
    description: Save the uv cache after the job
    required: false
    default: "auto"
runs:
  using: composite
  steps:
    - uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78
      with:
        enable-cache: ${{ inputs.enable-cache }}
        save-cache: ${{ inputs.save-cache }}
